version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    command: ["--dev", "--bind", "0.0.0.0"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
      LIVEKIT_REDIS_ADDRESS: redis:6379
    depends_on:
      - redis

  sip:
    image: livekit/sip:latest
    depends_on:
      - livekit
      - redis
    environment:
      SIP_CONFIG_BODY: |
        api_key: 'devkey'
        api_secret: 'secret'
        ws_url: 'ws://livekit:7880'
        redis:
          address: 'redis:6379'
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug

  egress:
    image: livekit/egress:latest
    depends_on:
      - redis
      - livekit
    environment:
      EGRESS_CONFIG_FILE: /config/egress.yaml
    volumes:
      - ./egress.yaml:/config/egress.yaml
      - ./output-recordings:/out

volumes:
  redis_data:
